version: 1.1.9.{build}-{branch}
configuration: Release
platform: x64
init:
  - cmd: >-
      choco install wget
environment:
  CVXOPT_BLAS_LIB: openblaspy
  CVXOPT_LAPACK_LIB: openblaspy
  CVXOPT_BLAS_LIB_DIR: c:\projects\cvxopt
  CVXOPT_BLAS_EXTRA_LINK_ARGS: -lgfortran;-lquadmath
  CVXOPT_SUITESPARSE_SRC_DIR: SuiteSparse
  matrix:
    - PYTHON: C:\Python27-x64
      PYTHON_VERSION: 27
    - PYTHON: C:\Python34-x64
      PYTHON_VERSION: 34
install:
  - cmd: >-
      set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

      wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.3.tar.gz && "C:\Program Files\7-Zip\7z" x SuiteSparse-4.5.3.tar.gz && "C:\Program Files\7-Zip\7z" x SuiteSparse-4.5.3.tar

      wget https://bitbucket.org/carlkl/mingw-w64-for-python/downloads/OpenBLAS-0.2.17_amd64.7z && mkdir openblas && "C:\Program Files\7-Zip\7z" x OpenBLAS-0.2.17_amd64.7z -aoa -oopenblas

      copy openblas\amd64\lib\libopenblaspy.a libopenblaspy.a

      python --version

      python -c "import struct; print(struct.calcsize('P') * 8)"

      pip install --disable-pip-version-check --user --upgrade pip

      pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy

      pip install wheel nose
build_script:
  - cmd: >-
      python setup.py build --compiler=mingw32

      python setup.py install

      python setup.py bdist_wheel
test_script:
  - cmd: >-
      python -c "from cvxopt import blas,lapack,cholmod,umfpack"

      nosetests
artifacts:
  - path: dist/*.whl
